export const Playlist = [
   {
      playlist: "main",
      nameid: "Guilt",
      author: "Nero",
      album: "Welcome Reality",
      time: "4:44",
      title: "",
    },
    {
      playlist: "main",
      nameid: "Elektro",
      author: "Dynoro, Outwork, Mr. Gee",
      album: "Elektro",
      time: "2:22",
      title: "",
    },
    {
      playlist: "main",
      nameid: "I’m Fire",
      author: "Ali Bakgor",
      album: "I’m Fire",
      time: "2:22",
      title: "",
    },
    {
      playlist: "main",
      nameid: "Non Stop",
      author: "Стоункат, Psychopath",
      album: "Non Stop",
      time: "4:12",
      title: "(Remix)",
    },
    {
      playlist: "main",
      nameid: "Run Run",
      author: "Jaded, Will Clarke, AR/CO",
      album: "Run Run",
      time: "2:54",
      title: "(feat. AR/CO)",
    },
    {
      playlist: "main",
      nameid: "Eyes on Fire",
      author: "Blue Foundation, Zeds Dead",
      album: "Eyes on Fire",
      time: "5:20",
      title: "(Zeds Dead Remix)",
    },
    {
      playlist: "main",
      nameid: "Mucho Bien",
      author: "HYBIT, Mr. Black, Offer Nissim, Hi Profile",
      album: "Mucho Bien",
      time: "3:41",
      title: "(Hi Profile Remix)",
    },
    {
      playlist: "main",
      nameid: "Knives n Cherries",
      author: "minthaze",
      album: "Captivating",
      time: "1:48",
      title: "",
    },
    {
      playlist: "main",
      nameid: "How Deep Is Your Love",
      author: "Calvin Harris, Disciples",
      album: "How Deep Is Your Love",
      time: "3:32",
      title: "",
    },
    {
      playlist: "main",
      nameid: "Morena",
      author: "Tom Boxer",
      album: "Soundz Made in Romania",
      time: "3:36",
      title: "",
    },
  {
    playlist: "1",
    nameid: "Guilt",
    author: "Nero",
    album: "Welcome Reality",
    time: "4:44",
    title: "",
  },
  {
    playlist: "1",
    nameid: "Elektro",
    author: "Dynoro, Outwork, Mr. Gee",
    album: "Elektro",
    time: "2:22",
    title: "",
  },
  {
    playlist: "1",
    nameid: "I’m Fire",
    author: "Ali Bakgor",
    album: "I’m Fire",
    time: "2:22",
    title: "",
  },
  {
    playlist: "1",
    nameid: "Non Stop",
    author: "Стоункат, Psychopath",
    album: "Non Stop",
    time: "4:12",
    title: "(Remix)",
  },
  {
    playlist: "1",
    nameid: "Run Run",
    author: "Jaded, Will Clarke, AR/CO",
    album: "Run Run",
    time: "2:54",
    title: "(feat. AR/CO)",
  },
  {
    playlist: "1",
    nameid: "Eyes on Fire",
    author: "Blue Foundation, Zeds Dead",
    album: "Eyes on Fire",
    time: "5:20",
    title: "(Zeds Dead Remix)",
  },
  {
   playlist: "2",
   nameid: "Eyes on Fire",
   author: "Blue Foundation, Zeds Dead",
   album: "Eyes on Fire",
   time: "5:20",
   title: "(Zeds Dead Remix)",
 },{
   playlist: "2",
   nameid: "Eyes on Fire",
   author: "Blue Foundation, Zeds Dead",
   album: "Eyes on Fire",
   time: "5:20",
   title: "(Zeds Dead Remix)",
 },{
   playlist: "2",
   nameid: "Eyes on Fire",
   author: "Blue Foundation, Zeds Dead",
   album: "Eyes on Fire",
   time: "5:20",
   title: "(Zeds Dead Remix)",
 },
  {
    playlist: "1",
    nameid: "Mucho Bien",
    author: "HYBIT, Mr. Black, Offer Nissim, Hi Profile",
    album: "Mucho Bien",
    time: "3:41",
    title: "(Hi Profile Remix)",
  },
  {
   playlist: "3",
   nameid: "Mucho Bien",
   author: "HYBIT, Mr. Black, Offer Nissim, Hi Profile",
   album: "Mucho Bien",
   time: "3:41",
   title: "(Hi Profile Remix)",
 }, {
   playlist: "3",
   nameid: "Mucho Bien",
   author: "HYBIT, Mr. Black, Offer Nissim, Hi Profile",
   album: "Mucho Bien",
   time: "3:41",
   title: "(Hi Profile Remix)",
 }, {
   playlist: "3",
   nameid: "Mucho Bien",
   author: "HYBIT, Mr. Black, Offer Nissim, Hi Profile",
   album: "Mucho Bien",
   time: "3:41",
   title: "(Hi Profile Remix)",
 },
  {
    playlist: "1",
    nameid: "Knives n Cherries",
    author: "minthaze",
    album: "Captivating",
    time: "1:48",
    title: "",
  },
  {
    playlist: "1",
    nameid: "How Deep Is Your Love",
    author: "Calvin Harris, Disciples",
    album: "How Deep Is Your Love",
    time: "3:32",
    title: "",
  },
  {
   playlist: "1",
   nameid: "Morena",
   author: "Tom Boxer",
   album: "Soundz Made in Romania",
   time: "3:36",
   title: "",
 },{
   playlist: "my",
   nameid: "Morena",
   author: "Tom Boxer",
   album: "Soundz Made in Romania",
   time: "3:36",
   title: "",
 },{
   playlist: "my",
   nameid: "Morena",
   author: "Tom Boxer",
   album: "Soundz Made in Romania",
   time: "3:36",
   title: "",
 },{
   playlist: "my",
   nameid: "Morena",
   author: "Tom Boxer",
   album: "Soundz Made in Romania",
   time: "3:36",
   title: "",
 },{
   playlist: "my",
   nameid: "Morena",
   author: "Tom Boxer",
   album: "Soundz Made in Romania",
   time: "3:36",
   title: "",
 },
  
];

export const  nameOfPlaylist = [
   {
      playlist: "main",
      name: "Треки"
   },
   {
      playlist: "1",
      name: "Плейлист дня"
   },
   {
      playlist: "2",
      name: "100 танцевальных хитов"
   },
   {
      playlist: "3",
      name: "Инди-заряд"
   },
   {
      playlist: "my",
      name: "Мой плейлист"
   }
   
]